info:
  app:
    name: one
    description: Service One

server:
  port: ${PORT_TO_EXPOSE:0}

spring:
  cloud:
    config:
      enabled: false

eureka:
  instance:
      preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${discovery-host}:${discovery-port}/eureka/

logging:
  level:
    ROOT: INFO
    com.epam.javacc.microservices: DEBUG
