server:
  port: ${discovery-port}

spring:
  cloud:
    config:
      enabled: false

endpoints:
    restart:
        enabled: true
    shutdown:
        enabled: true
    health:
        enabled: true
        sensitive: false

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
