info:
  component: Zuul Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  routes:
    one: /one/**
    two: /two/**

ribbon:
  #timeout applies only to REST request, not the wrapping Hystrix command
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1

# allows to make up to 2 REST request inside a command. Note: consider startup delay in services
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 20000

server:
  port: ${apigateway-port}

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

multipart:
  maxFileSize: 2048KB
  maxRequestSize: 2048KB

eureka:
  instance:
      preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${discovery-host}:${discovery-port}/eureka/